### ISSUE TITLE
Update saving data use case

### ISSUE THREAD

**Issue by raysonkoh** [AY2021S1-CS2103T-F11-4/tp#112]
AC:
1. Update statement 1 of saving data use case to be less implementation-focused. 
Statement 1: User enters a valid command that alters data (client add, client delete, client note add, etc).
2. Add numbering for use cases.

**Comment by tankangliang** [comment]
While updating this, could you add in numbering for the use cases as well? Then this statement can refer to other use cases as an example.

**Comment by raysonkoh** [comment]
Okay, I have updated the issue description.
