### ISSUE TITLE
Store Country Notes in JSON

### ISSUE THREAD

**Issue by raysonkoh** [AY2021S1-CS2103T-F11-4/tp#145]

**Comment by raysonkoh** [comment]
Current plan of action after discussion with @rtshkmr. This is a sample of how `notes` are going to be stored in JSON.
```
notes: [{
  contents: "some contents",
  tags: ["tag1", tag2"],
  client: "katya", // means this is client note
  country: null
}, {
  contents: "some contents2",
  tags: ["tag1", tag2"],
  client: null,
  country: "SG" // means this is country note
}]
```
Benefits of this implementation would be:
1. That there would only be 1 class that deals with json notes (irrespective of whether it is a client or a country note). 
2. Existing JSON client class does not need to be changed.

Possible issues:
1. Cannot uniquely identify `clients` by their name at the moment.

**Comment by qwoprocks** [comment]
>     1. Cannot uniquely identify `clients` by their name at the moment.

Possible fix: store the client as a string containing "\<client name\> \<client email\>", as we can use isSameClient method of Client to match the clients and notes.

**Comment by raysonkoh** [comment]
Putting it here in case I forget in the future:

Some major changes to be made:

1. Create new class `CountryNote` that inherits from `Note`. It stores the `Country`.
2. Add `isClientNote` method in `Note` to differentiate client and country notes. This probably need to be refactored. Possible idea would be to have abstract `Note` class, and have `ClientNote` and `CountryNote` inherit from it. There can be an enum `NoteType` that indicates which type the `Note` object is.

Having `CountryNote` extends from `Note` allows use of polymorphic `List<? extends Note>` when converting to json objects.
