### ISSUE TITLE
Increase test coverage for files in .ui package

### ISSUE THREAD

**Issue by qwoprocks** [AY2021S1-CS2103T-F11-4/tp#162]
Currently the portion with the least coverage.
Will wait till @LeeEnHao is done before adding some tests.

**Comment by LeeEnHao** [comment]
I can help you do this since it there's a possibility I may be bringing down the test suite from AB4 if I can resolve the Robot [#335](https://github.com/nus-cs2103-AY2021S1/forum/issues/335).
