### ISSUE TITLE
Client Notes: Add in PREFIX for index to improve command parsing. 

### ISSUE THREAD

**Issue by rtshkmr** [AY2021S1-CS2103T-F11-4/tp#224]
Current implementation of parser for Client Note delete is a little convoluted and ugly right now. Should add in an prefix to improve this. 
Not the highest priority right now.

![image](https://user-images.githubusercontent.com/38996397/97095645-bb671d00-1694-11eb-8c0c-aadd300b41e4.png)

**Comment by tankangliang** [comment]
Moving to v1.4 due to low priority

**Comment by qwoprocks** [comment]
Not going to do this for v1.4, may consider as further extension.
